name: Docker Build

on: [push]

env:
  DOCKER_REPO: ghcr.io/reallyenglish-global/re-ci-tools
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          #cache-from: type=registry,ref=${{ env.DOCKER_REPO }}:buildcache
          #cache-to: type=registry,ref=${{ env.DOCKER_REPO }}:buildcache
          tags: |
            ${{ env.DOCKER_REPO }}:latest
